#import = [
#  "~/.config/alacritty/catppuccin-mocha.toml"
#]

live_config_reload = true 

[env]
TERM = "xterm-256color"

[font]
size = 22
normal = { family = "JetBrainsMono Nerd Font", style = "Light" }

[window]
startup_mode = "Maximized"

[mouse]
hide_when_typing = true
