import = [
  "~/.config/alacritty/catppuccin-mocha.toml"
]

live_config_reload = true 

[env]
TERM = "xterm-256color"

[font]
size = 15
normal = { family = "JetBrainsMonoNerdFont" }

[window]
startup_mode = "Fullscreen"


