# Desktop-specific configuration

################
### MONITORS ###
################

output DP-2 resolution auto scale 2

#############
### INPUT ###
#############

input "type:keyboard" {
    xkb_layout de
    xkb_options caps:escape
}

input "type:pointer" {
    pointer_accel -0.8
}

##################################
### STARTUP (desktop-specific) ###
##################################

exec_always swayosd-server -s ~/.config/swayosd/style.css
exec swayidle
