general {
    lock_cmd = pidof hyprlock || hyprlock
    before_sleep_cmd = loginctl lock-session
    after_sleep_cmd = hyprctl monitors -j | jq -r '.[].name' | xargs -I{} hyprctl dispatch dpms on {}
}

# Turn off all screens after 30s when locked
listener {
    timeout = 30
    on-timeout = if pidof hyprlock; then hyprctl monitors -j | jq -r '.[].name' | xargs -I{} hyprctl dispatch dpms off {}; fi
    on-resume = hyprctl monitors -j | jq -r '.[].name' | xargs -I{} hyprctl dispatch dpms on {}
}

# Lock screen after 5 minutes of inactivity
listener {
    timeout = 300
    on-timeout = loginctl lock-session
}

# Turn off all screens after 5 minutes when not locked
listener {
    timeout = 300
    on-timeout = if ! pidof hyprlock; then hyprctl monitors -j | jq -r '.[].name' | xargs -I{} hyprctl dispatch dpms off {}; fi
    on-resume = hyprctl monitors -j | jq -r '.[].name' | xargs -I{} hyprctl dispatch dpms on {}
}
