format = """
[](blue)\
$python\
$directory\
$git_branch\
$git_status\
$docker_context\
[ ](blue)\
"""

# disable blank lines
add_newline = false

# Sets user-defined palette
palette = "catppuccin_mocha"

[python]
style = "fg:base bg:blue"
format = '[(${symbol}\($virtualenv\)) ]($style)'
symbol = "🐍"

[directory]
style = "fg:base bg:blue"
format = "[$path]($style)"
truncation_length = 3

[docker_context]
symbol = " "
style = "fg:base bg:blue"
format = '[$symbol $context]($style)'

[git_branch]
symbol = ""
style = "fg:base bg:blue"
format = '[ $symbol $branch]($style)'

[git_status]
style = "fg:base bg:blue"
format = '[ $all_status$ahead_behind]($style)'

[palettes.catppuccin_mocha]
rosewater = "#f5e0dc"
flamingo = "#f2cdcd"
pink = "#f5c2e7"
mauve = "#cba6f7"
red = "#f38ba8"
maroon = "#eba0ac"
peach = "#fab387"
yellow = "#f9e2af"
green = "#a6e3a1"
teal = "#94e2d5"
sky = "#89dceb"
sapphire = "#74c7ec"
blue = "#89b4fa"
lavender = "#b4befe"
text = "#cdd6f4"
subtext1 = "#bac2de"
subtext0 = "#a6adc8"
overlay2 = "#9399b2"
overlay1 = "#7f849c"
overlay0 = "#6c7086"
surface2 = "#585b70"
surface1 = "#45475a"
surface0 = "#313244"
base = "#1e1e2e"
mantle = "#181825"
crust = "#11111b"
