set -g status-style bg="#191622"
set-window-option -g window-status-current-format '#[fg=blue]#I:#W#[default]'

# status bar on top
#set -g status-position top

# reload config
bind r source-file ~/.config/tmux/tmux.conf

# prevend the esc bug
set -sg escape-time 10

# Bind Alt + h,l to switch to the next window or prev window
bind -n M-h select-window -p
bind -n M-l select-window -n

# map Alt + 1-9, create new window in the same path as current window 
bind -n M-1 if-shell 'tmux select-window -t :1' 'select-window -t :1' 'new-window -c "#{pane_current_path}" -t :1'
bind -n M-2 if-shell 'tmux select-window -t :2' 'select-window -t :2' 'new-window -c "#{pane_current_path}" -t :2'
bind -n M-3 if-shell 'tmux select-window -t :3' 'select-window -t :3' 'new-window -c "#{pane_current_path}" -t :3'
bind -n M-4 if-shell 'tmux select-window -t :4' 'select-window -t :4' 'new-window -c "#{pane_current_path}" -t :4'
bind -n M-5 if-shell 'tmux select-window -t :5' 'select-window -t :5' 'new-window -c "#{pane_current_path}" -t :5'
bind -n M-6 if-shell 'tmux select-window -t :6' 'select-window -t :6' 'new-window -c "#{pane_current_path}" -t :6'
bind -n M-7 if-shell 'tmux select-window -t :7' 'select-window -t :7' 'new-window -c "#{pane_current_path}" -t :7'
bind -n M-8 if-shell 'tmux select-window -t :8' 'select-window -t :8' 'new-window -c "#{pane_current_path}" -t :8'
bind -n M-9 if-shell 'tmux select-window -t :9' 'select-window -t :9' 'new-window -c "#{pane_current_path}" -t :9'

# Set the base index for windows to 1
set -g base-index 1

%if #{TMUX}
# If running inside tmux ($TMUX is set), then change the status line to red
set -g status-bg red
%endif

# Enable RGB colour if running in xterm(1)
set-option -sa terminal-overrides ",xterm*:Tc"

# Change the default $TERM to tmux-256color
set -g default-terminal "tmux-256color"

# No bells at all
set -g bell-action none

# Keep windows around after they exit
#set -g remain-on-exit on

# Change the prefix key to C-a
unbind C-b
set -g prefix C-a
bind C-a send-prefix

# switch panes with Alt-hjkl
bind -n M-h select-pane -L
bind -n M-l select-pane -R
bind -n M-j select-pane -D
bind -n M-k select-pane -U

# Turn the mouse on, but without copy mode dragging
set -g mouse on
unbind -n MouseDrag1Pane
unbind -Tcopy-mode MouseDrag1Pane

set -g pane-active-border-style bg=default,fg=default
set -g pane-border-style fg=black
